routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

# Users系の処理を呼び出す用
Route::resource('users', 'UsersController');
// 会員削除確認画面のルート設定
Route::get('users','UsersController@delete_confirm')->name('users.delete_confirm');
# Messages系の処理を呼び出す用
Route::resource('messages', 'MessagesController');
# Comments系の処理を呼び出す用
Route::resource('comments', 'CommentsController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/flashMessage.blade.php
@foreach ($errors->all() as $error)
    <div class="alert alert-danger">
        {{$error}}
    </div>
@endforeach

@if (session('success'))
    <div class="success-message alert alert-success" id="success-massage">
        {{session('success')}}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

resources/views/home.blade.php
@extends('layout')

<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
<style type="text/css">
	#scrollTop {
		position: fixed;
		right: 50px;
		bottom: 50px;
		background-color: #DCDCDC;
		width: 50px;
  		height: 50px;
  		border-radius: 50%;
		color: gray;
  		line-height: 50px;
  		text-align: center;
		display: none;
	}
	#scrollTop:hover {
  		cursor: pointer;
  		opacity: 0.7;
	}
</style>
<title>ホーム</title>

@section('content')
<div class="container">
  <section class="section">
    <div class="column is-8 is-offset-2">

    <!-- 検索フォーム部 -->
    <form method="GET" action="{{ route('home') }}">
      <input type="search" class="input column is-8 is-offset-2" placeholder="検索ワードを入力" name="search" value="@if (isset($search)) {{ $search }} @endif">
      <div class="column is-8 is-offset-2 d-flex justify-content-center">
          <button type="submit" class="btn btn-primary mr-4">検索</button>
          <button class="btn btn-secondary">
              <a href="{{ route('home') }}" class="text-white">
                クリア
              </a>
          </button>
      </div>
    </form>

    <!-- フラッシュメッセージ部 -->
    @include('flashMessage')

      @foreach($messages as $message)
        <div class="box media">
          <figure class="media-left">
            <i class="fas fa-clipboard-list"></i>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>{{ $message->title }}</strong>
              </p>
              <p>
                {{ $message->text }}
              </p>
              <p class="content-option-space">
                {{ $message->user->name }} / {{ $message->created_at }}
              </p>

              <!-- 投稿ボタン部 -->
              <!-- ユーザー認証処理 -->
              @if (!Auth::guest() && Auth::user()->id == $message->user_id)
                <div class="d-flex justify-content-end">
                  <!-- 編集ボタン -->
                  <div class="mr-2">
                    {!! Form::model($message, ['route' => ['messages.edit', $message->id], 'method' => 'get']) !!}
                    @csrf
                      {!! Form::submit('編集', ['class' => 'btn btn-primary']) !!}
                    {!! Form::close() !!}
                  </div>
                  <!-- 削除ボタン -->
                  <div id="delete-btn-{{$message->id}}">
                    {!! Form::model($message, ['route' => ['messages.destroy', $message->id], 'method' => 'delete']) !!}
                    @csrf
                    @method('DELETE')
                      {!! Form::submit('削除', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                  </div>
                </div>
              @endif
            </div>
          </div>
        </div>

        @foreach($message->comments as $comment)
          <div class="column is-8 is-offset-4">
            <div class="box media">
              <figure class="media-left">
                <i class="fas fa-grin-beam"></i>
              </figure>
              <div class="media-content">
                <div class="content">
                  <p>
                    {{ $comment->text }}
                  </p>
                  <p class="content-option-space">
                    {{ $comment->user->name }} / {{ $comment->created_at }}
                  </p>

                  <!-- コメントボタン部 -->
                  <!-- ユーザー認証処理 -->
                  @if (!Auth::guest() && Auth::user()->id == $comment->user_id)
                    <div class="d-flex justify-content-end">
                      <!-- 編集ボタン -->
                      <div class="mr-2">
                        {!! Form::model($comment, ['route' => ['comments.edit', $comment->id], 'method' => 'get']) !!}
                        @csrf
                          {!! Form::submit('編集', ['class' => 'btn btn-primary']) !!}
                        {!! Form::close() !!}
                      </div>
                      <!-- 削除ボタン -->
                      <div id="delete-btn-{{$comment->id}}">
                        {!! Form::model($comment, ['route' => ['comments.destroy', $comment->id], 'method' => 'delete']) !!}
                        @csrf
                        @method('DELETE')
                          {!! Form::submit('削除', ['class' => 'btn btn-danger']) !!}
                        {!! Form::close() !!}
                      </div>
                    </div>
                  @endif
                </div>
              </div>
            </div>
          </div>
        @endforeach

        {!! Form::open(['url' => '/comments']) !!}
          <!-- hidden属性でメッセージIDとメッセージタイトルをセット -->
          {!! Form::hidden('message_id', $message->id) !!}
          {!! Form::hidden('message_title', $message->title) !!}
          <div class="column is-6 is-offset-6">
            <div class="field">
              <label for='label'>
                コメント :
              </label>
              <p class="control">
                {!! Form::textarea('text', null, ['class' => 'input is-medium', 'style' => 'height: 100px;']) !!}
              </p>
            </div>
            <div class="field">
              <p class="control" style="text-align: right;">
                {!! Form::submit('コメント投稿', ['class' => 'button is-primary is-medium']) !!}
              </p>
            </div>
          </div>
        {!! Form::close() !!}
      @endforeach
    </div>
    <!-- ページングリンク部 -->
    <div class="d-flex justify-content-center">
      {{ $messages->appends(request()->input())->links() }}
    </div>
	<!-- 画面上部へのスクロールボタン部 -->
	<div id="scrollTop">TOPへ</div>
  </section>
</div>
<script src="{{ asset('/js/delete.js') }}"></script>
<script src="{{ asset('/js/success.js') }}"></script>
<script src="{{ asset('/js/scrollTop.js') }}"></script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE HTML>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Laravel掲示板</title>

    <script src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" defer="defer"></script>
    <script src="/js/app.js" defer></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <link href="/css/app.css" rel="stylesheet" type="text/css">
    <link href="/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <!-- ログインをしていないときのナビメニュー -->
                    @guest
                        <li class="nav-item">
                            {!! link_to("home", 'ホーム画面', ['class' => "text-light btn btn-info d-flex align-items-center mr-3"]) !!}
                        </li>
                        
                        <li class="nav-item">
                            {!! link_to("users/create", 'ユーザー登録', ['class' => "text-light btn btn-info d-flex align-items-center mr-3"]) !!}
                        </li>
                    @else
                    <!-- ログインをしているときのナビメニュー -->
                        <a class="navbar-brand text-light btn btn-info d-flex align-items-center mr-3" href="{{ url('home') }}">
                            ホーム画面
                        </a>
                        <a class="navbar-brand text-light btn btn-info d-flex align-items-center mr-3" href="{{ url('messages/create') }}">
                            新規投稿
                        </a>
                        <li class="nav-item dropdown d-flex align-items-center btn btn-secondary btn-sm">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <!-- ログアウトリンク -->
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    ログアウト
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                                
                                <!-- ユーザー編集リンク -->
                                <a class="dropdown-item" href="{{ route('users.edit', Auth::user()->id) }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('user-edit-form').submit();">
                                    ユーザー設定
                                </a>
                                
                                <form id="user-edit-form" action="{{ route('users.edit', Auth::user()->id) }}" method="GET" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    @yield('content')

</body>
</html>